# Generated by Django 4.0.3 on 2022-04-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('employer_image', models.ImageField(upload_to='images/')),
                ('established', models.BigIntegerField()),
                ('about', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employer',
            },
        ),
    ]
