# Generated by Django 4.0.3 on 2022-04-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0002_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('candidate_image', models.ImageField(upload_to='images/')),
                ('technologies', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
    ]
