# Generated by Django 4.0.3 on 2022-05-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyapp', '0003_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('salary', models.BigIntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('skills_required', models.CharField(max_length=100)),
                ('responsibility', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('interview_date', models.DateField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyapp.employer')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='')),
                ('datetime', models.DateTimeField()),
                ('job_status', models.IntegerField(default=0)),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyapp.add_notification')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyapp.candidate')),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('technologies', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('salary', models.BigIntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyapp.candidate')),
            ],
            options={
                'db_table': 'preference',
            },
        ),
    ]
